apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-cluster-resources-reader
  namespace: {{ .Values.global.clusterResourcesNamespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-cluster-resources-reader
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-controller
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-external-webhooks-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-cluster-resources-admin
  namespace: {{ .Values.global.clusterResourcesNamespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-cluster-resources-admin
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-admin
