{{- if .Values.api.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-api
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-api
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-api
{{- end }}
