apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-admin
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-admin
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-role-token-reader
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-role-token-reader
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-user
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-viewer
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-project-creator
