{{- if .Values.global.createSharedResourcesNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.sharedResourcesNamespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
{{- end }}
