blank_issues_enabled: true

contact_links:
  - name: Have you read the docs?
    url: https://docs.kargo.io
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/akuity/kargo/discussions/new
    about: Ask a question or start a discussion about Kargo
  - name: Chat on Discord
    url: https://discord.gg/dHJBZw6ewT
    about: Maybe chatting with the community can help
