{{- if and .Values.api.enabled .Values.api.oidc.enabled .Values.api.oidc.dex.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-dex-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.dexServer.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.annotations) .Values.api.oidc.dex.serviceAccount.annotations) }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
