{{- if and .Values.api.enabled .Values.api.oidc.enabled .Values.api.oidc.dex.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kargo.dexServer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.dexServer.labels" . | nindent 4 }}
{{- end }}
