{{- if .Values.global.systemResources.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ quote .Values.global.systemResources.namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
{{- end }}
