{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.controller.logLevel }}
  {{- if .Values.controller.shardName }}
  SHARD_NAME: {{ .Values.controller.shardName }}
  {{- end }}
  {{- if .Values.kubeconfigSecrets.kargo }}
  KUBECONFIG: /etc/kargo/kubeconfigs/kubeconfig.yaml
  {{- end }}
  GLOBAL_CREDENTIALS_NAMESPACES: {{ quote (join "," .Values.controller.globalCredentials.namespaces) }}
  ARGOCD_INTEGRATION_ENABLED: {{ quote .Values.controller.argocd.integrationEnabled }}
  {{- if .Values.controller.argocd.integrationEnabled }}
  {{- if .Values.kubeconfigSecrets.argocd }}
  ARGOCD_KUBECONFIG: /etc/kargo/kubeconfigs/argocd-kubeconfig.yaml
  {{- end }}
  ARGOCD_NAMESPACE: {{ .Values.controller.argocd.namespace }}
  ARGOCD_WATCH_ARGOCD_NAMESPACE_ONLY: {{ quote .Values.controller.argocd.watchArgocdNamespaceOnly }}
  {{- end }}
  ROLLOUTS_INTEGRATION_ENABLED: {{ quote .Values.controller.rollouts.integrationEnabled }}
  {{- if .Values.controller.rollouts.integrationEnabled }}
  {{- if .Values.kubeconfigSecrets.rollouts }}
  ROLLOUTS_KUBECONFIG: /etc/kargo/kubeconfigs/rollouts-kubeconfig.yaml
  {{- end }}
  ROLLOUTS_ANALYSIS_RUNS_NAMESPACE: {{ quote .Values.controller.rollouts.analysisRunsNamespace }}
  ROLLOUTS_CONTROLLER_INSTANCE_ID: {{ quote .Values.controller.rollouts.controllerInstanceID }}
  {{- end }}
{{- end }}
