{{- if .Values.rbac.installGlobalResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8sta.server.fullname" . }}
  labels:
    {{- include "k8sta.labels" . | nindent 4 }}
    {{- include "k8sta.server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8sta.akuity.io
  resources:
  - tickets
  verbs:
  - create
{{- end }}
