{{- if and .Values.externalWebhooksServer.enabled .Values.externalWebhooksServer.httproute.enabled -}}
{{- $webhookPort := ternary 443 80 .Values.externalWebhooksServer.tls.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kargo-external-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.externalWebhooksServer.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.global.annotations) .Values.externalWebhooksServer.httproute.annotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.externalWebhooksServer.httproute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  hostnames:
    - {{ quote .Values.externalWebhooksServer.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: kargo-external-webhooks-server
          port: {{ $webhookPort }}
          weight: 1
{{- end }}